# Generated by Django 4.1 on 2022-09-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='table_name',
            field=models.TextField(default='Book'),
        ),
        migrations.AddField(
            model_name='post',
            name='table_name',
            field=models.TextField(default='Post'),
        ),
    ]
